spring:
  application:
    name: backend-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/backend_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
